apiVersion: v1
kind: Template
metadata:
  name: iscsi
parameters:
- name: GITURI
  value: https://github.com/edseymour/iscsi-openshift.git
  displayName: Git URI
  description: Source code location
  required: true
- description: Webhook secret used to in webhook build triggers
  displayName: Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: WEBHOOK_SECRET
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: iscsi
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: iscsi:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: docker
      git:
        uri: ${GITURI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:latest
          namespace: openshift
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${WEBHOOK_SECRET}
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: iscsi
