apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-lun%lun
  labels:
    kind: iscsi
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: %size
  iscsi:
    targetPortal: "192.168.1.12:3260"
    iqn: "iqn.2016-04.cluster.local:storage.target00"
    lun: %lun
    fsType: "ext4"
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
status: {}
